## Import Libraries

In [24]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Load The Dataset

In [25]:
# Creating the Dataframe
df=pd.read_csv('Dataset .csv')
df.head(1)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314

## Data Pre-processing Steps

In [26]:
# Droping un-necessary Columns
df.drop('Restaurant ID', axis=1, inplace=True) 
df.drop('Country Code', axis=1, inplace=True) 
df.drop('City', axis=1, inplace=True) 
df.drop('Address', axis=1, inplace=True) 
df.drop('Locality', axis=1, inplace=True) 
df.drop('Locality Verbose', axis=1, inplace=True) 
df.drop('Longitude', axis=1, inplace=True) 
df.drop('Latitude', axis=1, inplace=True) 
df.drop('Currency', axis=1, inplace=True) 
df.drop('Has Table booking', axis=1, inplace=True) 
df.drop('Has Online delivery', axis=1, inplace=True) 
df.drop('Is delivering now', axis=1, inplace=True) 
df.drop('Switch to order menu', axis=1, inplace=True) 
df.drop('Price range', axis=1, inplace=True) 
df.drop('Aggregate rating', axis=1, inplace=True) 
df.drop('Rating color', axis=1, inplace=True) 
df.drop('Rating text', axis=1, inplace=True) 
df.drop('Votes', axis=1, inplace=True)
df

,Restaurant Name,Cuisines,Average Cost for two
0,Le Petit Souffle,"French, Japanese, Desserts",1100
1,Izakaya Kikufuji,Japanese,1200
2,Heat - Edsa Shangri-La,"Seafood, Asian, Filipino, Indian",4000
3,Ooma,"Japanese, Sushi",1500
4,Sambo Kojin,"Japanese, Korean",1500
...,...,...,...
9546,Naml۱ Gurme,Turkish,80
9547,Ceviz A��ac۱,"World Cuisine, Patisserie, Cafe",105
9548,Huqqa,"Italian, World Cuisine",170
9549,A���k Kahve,Restaurant Cafe,120
9550,Walter's Coffee Roastery,Cafe,55

In [28]:
# Checking for missing values
df.isnull().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

In [29]:
df.dropna(inplace=True)

In [30]:
df.shape

(9542, 3)

In [31]:
# Checking missing vaalues for each col
missing_values = df.isna().sum() 
missing_values_column = df['Restaurant Name'].isna().sum() 
missing_values_column = df['Cuisines'].isna().sum() 
missing_values_column = df['Average Cost for two'].isna().sum()

In [32]:
df_cleaned = df.dropna() 
df_cleaned = df.dropna(subset=['Restaurant Name']) 
df_cleaned = df.dropna(subset=['Cuisines']) 
df_cleaned = df.dropna(subset=['Average Cost for two'])

In [33]:
df.describe(include="all")

        Restaurant Name      Cuisines  Average Cost for two
count              9542          9542           9542.000000
unique             7437          1825                   NaN
top     Cafe Coffee Day  North Indian                   NaN
freq                 83           936                   NaN
mean                NaN           NaN           1200.326137
std                 NaN           NaN          16128.743876
min                 NaN           NaN              0.000000
25%                 NaN           NaN            250.000000
50%                 NaN           NaN            400.000000
75%                 NaN           NaN            700.000000
max                 NaN           NaN         800000.000000

In [41]:
# Converting Categorical data to NUmerical
from sklearn.preprocessing import LabelEncoder 
label_encoder = LabelEncoder() 
df['Restaurant Name'] = label_encoder.fit_transform(df['Restaurant Name']) 
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])
df

      Restaurant Name  Cuisines  Average Cost for two
0                3742       920                  1100
1                3167      1111                  1200
2                2892      1671                  4000
3                4700      1126                  1500
4                5515      1122                  1500
...               ...       ...                   ...
9546             4436      1813                    80
9547             1310      1824                   105
9548             3063      1110                   170
9549              512      1657                   120
9550             7231       331                    55

[9542 rows x 3 columns]

## Splitting the dataset into Training and Testing set

In [36]:
# Create X and Y
X = df[['Restaurant Name', 'Average Cost for two']] 
Y = df['Cuisines']

In [37]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(X)
X= scaler.transform(X)

In [38]:
from sklearn.model_selection import train_test_split
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,random_state=10)

## Building Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression(multi_class="multinomial")
#train the model object
classifier.fit(X_train,Y_train)      # fit is the function that is used for training the data
Y_pred = classifier.predict(X_test)
print(Y_pred)

[1306 1306 1306 ... 1306 1306 1306]

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print("Classification report: ")
print(classification_report(Y_test,Y_pred))
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         2
          26       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          34       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         1
          47       0.00      0.00      0.00         1
          49       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         3
          55       0.00      0.00      0.00         1
          58       0.00      0.00      0.00        13
          69       0.00      0.00      0.00         1
          81       0.00      0.00      0.00         1
          85       0.00      0.00      0.00         1
          89       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         2
         101       0.00      0.00      0.00         1
         104       0.00      0.00      0.00         2
         112       0.00      0.00      0.00         1
         115       0.00      0.00      0.00         2
         121       0.00      0.00      0.00         2
         123       0.00      0.00      0.00         1
         124       0.00      0.00      0.00         1
         134       0.00      0.00      0.00         1
         143       0.00      0.00      0.00         1
         152       0.00      0.00      0.00         1
         153       0.00      0.00      0.00         1
         158       0.00      0.00      0.00         1
         159       0.00      0.00      0.00         2
         168       0.00      0.00      0.00         3
         170       0.00      0.00      0.00         1
         176       0.00      0.00      0.00         1
         177       0.00      0.00      0.00        44
         178       0.00      0.00      0.00         1
         181       0.00      0.00      0.00         1
         184       0.00      0.00      0.00         1
         186       0.00      0.00      0.00        29
         188       0.00      0.00      0.00         1
         191       0.00      0.00      0.00        15
         195       0.00      0.00      0.00         1
         199       0.00      0.00      0.00         1
         201       0.00      0.00      0.00        25
         205       0.00      0.00      0.00         1
         211       0.00      0.00      0.00         1
         213       0.00      0.00      0.00         1
         216       0.00      0.00      0.00         1
         217       0.00      0.00      0.00         1
         220       0.00      0.00      0.00         1
         222       0.00      0.00      0.00         1
         223       0.00      0.00      0.00         2
         225       0.00      0.00      0.00         1
         226       0.00      0.00      0.00         3
         230       0.00      0.00      0.00        12
         233       0.00      0.00      0.00         2
         234       0.00      0.00      0.00         1
         236       0.00      0.00      0.00         1
         243       0.00      0.00      0.00        11
         246       0.00      0.00      0.00         1
         249       0.00      0.00      0.00         1
         251       0.00      0.00      0.00         4
         255       0.00      0.00      0.00         2
         257       0.00      0.00      0.00         2
         258       0.00      0.00      0.00         1
         268       0.00      0.00      0.00         1
         274       0.00      0.00      0.00         1
         276       0.00      0.00      0.00         1
         277       0.00      0.00      0.00         1
         283       0.00      0.00      0.00         1
         284       0.00      0.00      0.00         1
         285       0.00      0.00      0.00         2
         290       0.00      0.00      0.00         1
         294       0.00      0.00      0.00         3
         297       0.00      0.00      0.00         1
         298       0.00      0.00      0.00         1
         307       0.00      0.00      0.00         4
         309       0.00      0.00      0.00         1
         310       0.00      0.00      0.00         7
         311       0.00      0.00      0.00         1
         315       0.00      0.00      0.00         1
         323       0.00      0.00      0.00         1
         327       0.00      0.00      0.00         1
         329       0.00      0.00      0.00         1
         331       0.00      0.00      0.00        65
         332       0.00      0.00      0.00         1
         335       0.00      0.00      0.00         1
         336       0.00      0.00      0.00         1
         337       0.00      0.00      0.00         1
         340       0.00      0.00      0.00         1
         344       0.00      0.00      0.00         4
         346       0.00      0.00      0.00         1
         352       0.00      0.00      0.00         1
         357       0.00      0.00      0.00         1
         361       0.00      0.00      0.00         1
         363       0.00      0.00      0.00         1
         364       0.00      0.00      0.00         1
         367       0.00      0.00      0.00         1
         370       0.00      0.00      0.00         4
         371       0.00      0.00      0.00         1
         372       0.00      0.00      0.00         2
         379       0.00      0.00      0.00         1
         381       0.00      0.00      0.00         1
         382       0.00      0.00      0.00         1
         386       0.00      0.00      0.00         1
         390       0.00      0.00      0.00         1
         394       0.00      0.00      0.00         1
         397       0.00      0.00      0.00         1
         400       0.00      0.00      0.00         3
         402       0.00      0.00      0.00         1
         404       0.00      0.00      0.00         1
         405       0.00      0.00      0.00         1
         407       0.00      0.00      0.00         1
         417       0.00      0.00      0.00         1
         418       0.00      0.00      0.00         1
         420       0.00      0.00      0.00         5
         425       0.00      0.00      0.00         1
         426       0.00      0.00      0.00         1
         427       0.00      0.00      0.00         2
         433       0.00      0.00      0.00         1
         437       0.00      0.00      0.00         1
         441       0.00      0.00      0.00         1
         444       0.00      0.00      0.00         1
         445       0.00      0.00      0.00         1
         451       0.00      0.00      0.00         1
         461       0.00      0.00      0.00         1
         462       0.00      0.00      0.00         1
         463       0.00      0.00      0.00         1
         464       0.00      0.00      0.00         1
         465       0.00      0.00      0.00         2
         467       0.00      0.00      0.00         1
         468       0.00      0.00      0.00         1
         469       0.00      0.00      0.00         1
         471       0.00      0.00      0.00         1
         486       0.00      0.00      0.00         1
         487       0.00      0.00      0.00         1
         491       0.00      0.00      0.00         1
         497       0.00      0.00      0.00        64
         500       0.00      0.00      0.00         1
         502       0.00      0.00      0.00         1
         507       0.00      0.00      0.00         1
         512       0.00      0.00      0.00         2
         516       0.00      0.00      0.00         1
         517       0.00      0.00      0.00         1
         518       0.00      0.00      0.00        19
         521       0.00      0.00      0.00         1
         522       0.00      0.00      0.00         1
         526       0.00      0.00      0.00         1
         528       0.00      0.00      0.00         1
         531       0.00      0.00      0.00         1
         533       0.00      0.00      0.00         1
         536       0.00      0.00      0.00         1
         544       0.00      0.00      0.00         1
         546       0.00      0.00      0.00         2
         548       0.00      0.00      0.00         1
         549       0.00      0.00      0.00        21
         552       0.00      0.00      0.00         1
         563       0.00      0.00      0.00         1
         564       0.00      0.00      0.00         1
         568       0.00      0.00      0.00         2
         576       0.00      0.00      0.00         1
         582       0.00      0.00      0.00         4
         583       0.00      0.00      0.00         1
         584       0.00      0.00      0.00         1
         588       0.00      0.00      0.00        10
         589       0.00      0.00      0.00         3
         591       0.00      0.00      0.00         1
         595       0.00      0.00      0.00         2
         598       0.00      0.00      0.00         1
         600       0.00      0.00      0.00         1
         604       0.00      0.00      0.00         1
         606       0.00      0.00      0.00         1
         608       0.00      0.00      0.00         1
         616       0.00      0.00      0.00         1
         618       0.00      0.00      0.00         2
         621       0.00      0.00      0.00         1
         622       0.00      0.00      0.00         1
         625       0.00      0.00      0.00         5
         626       0.00      0.00      0.00         2
         627       0.00      0.00      0.00         1
         634       0.00      0.00      0.00         1
         635       0.00      0.00      0.00         1
         650       0.00      0.00      0.00         1
         653       0.00      0.00      0.00         1
         660       0.00      0.00      0.00         2
         669       0.00      0.00      0.00         1
         670       0.00      0.00      0.00         1
         671       0.00      0.00      0.00         1
         672       0.00      0.00      0.00         1
         675       0.00      0.00      0.00         1
         682       0.00      0.00      0.00         2
         693       0.00      0.00      0.00         1
         703       0.00      0.00      0.00         1
         707       0.00      0.00      0.00         1
         709       0.00      0.00      0.00         1
         719       0.00      0.00      0.00         2
         722       0.00      0.00      0.00         4
         724       0.00      0.00      0.00         1
         729       0.00      0.00      0.00         1
         730       0.00      0.00      0.00         1
         731       0.00      0.00      0.00         1
         732       0.00      0.00      0.00         1
         734       0.00      0.00      0.00         1
         736       0.00      0.00      0.00         1
         738       0.00      0.00      0.00         1
         743       0.00      0.00      0.00         1
         746       0.00      0.00      0.00         1
         748       0.00      0.00      0.00         1
         758       0.00      0.00      0.00         9
         760       0.00      0.00      0.00         2
         761       0.00      0.00      0.00         1
         765       0.00      0.00      0.00         3
         766       0.00      0.00      0.00         1
         767       0.00      0.00      0.00         1
         768       0.00      0.00      0.00         1
         770       0.00      0.00      0.00         4
         772       0.00      0.00      0.00         1
         774       0.00      0.00      0.00         5
         775       0.00      0.00      0.00         1
         783       0.00      0.00      0.00         1
         784       0.00      0.00      0.00         1
         786       0.00      0.00      0.00         1
         787       0.00      0.00      0.00         1
         788       0.00      0.00      0.00         1
         791       0.00      0.00      0.00         3
         796       0.00      0.00      0.00         1
         798       0.00      0.00      0.00         1
         799       0.00      0.00      0.00         1
         802       0.00      0.00      0.00         2
         810       0.00      0.00      0.00         4
         813       0.00      0.00      0.00         1
         828       0.00      0.00      0.00        77
         831       0.00      0.00      0.00         1
         833       0.00      0.00      0.00         1
         834       0.00      0.00      0.00         9
         837       0.00      0.00      0.00        11
         841       0.00      0.00      0.00         5
         842       0.00      0.00      0.00         1
         843       0.00      0.00      0.00         1
         846       0.00      0.00      0.00         1
         849       0.00      0.00      0.00         1
         852       0.00      0.00      0.00         1
         853       0.00      0.00      0.00         1
         858       0.00      0.00      0.00         1
         859       0.00      0.00      0.00         1
         865       0.00      0.00      0.00        11
         867       0.00      0.00      0.00         1
         868       0.00      0.00      0.00         1
         871       0.00      0.00      0.00         1
         872       0.00      0.00      0.00         2
         874       0.00      0.00      0.00         1
         876       0.00      0.00      0.00         1
         878       0.00      0.00      0.00         3
         880       0.00      0.00      0.00         1
         882       0.00      0.00      0.00         1
         886       0.00      0.00      0.00         3
         895       0.00      0.00      0.00         8
         909       0.00      0.00      0.00         1
         912       0.00      0.00      0.00         1
         920       0.00      0.00      0.00         1
         923       0.00      0.00      0.00         1
         930       0.00      0.00      0.00         1
         932       0.00      0.00      0.00         1
         933       0.00      0.00      0.00         1
         937       0.00      0.00      0.00         1
         939       0.00      0.00      0.00         1
         940       0.00      0.00      0.00         1
         944       0.00      0.00      0.00         1
         946       0.00      0.00      0.00         1
         950       0.00      0.00      0.00         1
         951       0.00      0.00      0.00         3
         953       0.00      0.00      0.00         2
         954       0.00      0.00      0.00         1
         955       0.00      0.00      0.00         1
         956       0.00      0.00      0.00         1
         958       0.00      0.00      0.00         2
         959       0.00      0.00      0.00         1
         968       0.00      0.00      0.00         1
         969       0.00      0.00      0.00         1
         971       0.00      0.00      0.00         1
         972       0.00      0.00      0.00         3
         982       0.00      0.00      0.00        13
         983       0.00      0.00      0.00         1
         986       0.00      0.00      0.00        19
         987       0.00      0.00      0.00         1
         995       0.00      0.00      0.00         5
        1002       0.00      0.00      0.00         1
        1008       0.00      0.00      0.00         2
        1009       0.00      0.00      0.00         1
        1011       0.00      0.00      0.00         1
        1014       0.00      0.00      0.00         1
        1020       0.00      0.00      0.00         2
        1021       0.00      0.00      0.00         1
        1026       0.00      0.00      0.00         1
        1027       0.00      0.00      0.00         1
        1030       0.00      0.00      0.00         1
        1031       0.00      0.00      0.00        12
        1038       0.00      0.00      0.00         1
        1039       0.00      0.00      0.00         1
        1040       0.00      0.00      0.00         3
        1043       0.00      0.00      0.00         1
        1044       0.00      0.00      0.00         2
        1045       0.00      0.00      0.00         1
        1047       0.00      0.00      0.00         1
        1048       0.00      0.00      0.00         1
        1061       0.00      0.00      0.00         1
        1065       0.00      0.00      0.00         3
        1068       0.00      0.00      0.00         1
        1070       0.00      0.00      0.00         1
        1084       0.00      0.00      0.00         1
        1093       0.00      0.00      0.00         1
        1095       0.00      0.00      0.00         1
        1098       0.00      0.00      0.00         6
        1100       0.00      0.00      0.00         1
        1102       0.00      0.00      0.00         4
        1104       0.00      0.00      0.00         1
        1105       0.00      0.00      0.00         1
        1111       0.00      0.00      0.00         2
        1114       0.00      0.00      0.00         1
        1118       0.00      0.00      0.00         1
        1120       0.00      0.00      0.00         1
        1125       0.00      0.00      0.00         2
        1126       0.00      0.00      0.00         7
        1130       0.00      0.00      0.00         1
        1133       0.00      0.00      0.00         1
        1134       0.00      0.00      0.00         1
        1142       0.00      0.00      0.00         1
        1143       0.00      0.00      0.00         1
        1150       0.00      0.00      0.00         1
        1152       0.00      0.00      0.00         1
        1153       0.00      0.00      0.00         2
        1155       0.00      0.00      0.00         1
        1159       0.00      0.00      0.00         1
        1160       0.00      0.00      0.00         1
        1161       0.00      0.00      0.00         1
        1170       0.00      0.00      0.00         1
        1171       0.00      0.00      0.00         3
        1173       0.00      0.00      0.00         1
        1178       0.00      0.00      0.00         1
        1184       0.00      0.00      0.00         1
        1185       0.00      0.00      0.00         1
        1186       0.00      0.00      0.00         1
        1192       0.00      0.00      0.00         1
        1198       0.00      0.00      0.00         1
        1199       0.00      0.00      0.00         1
        1203       0.00      0.00      0.00         1
        1204       0.00      0.00      0.00         2
        1210       0.00      0.00      0.00         1
        1212       0.00      0.00      0.00         8
        1214       0.00      0.00      0.00         1
        1217       0.00      0.00      0.00         1
        1220       0.00      0.00      0.00         1
        1223       0.00      0.00      0.00         1
        1231       0.00      0.00      0.00         1